logLevel: info

rtsp: yes
rtspTransports: [tcp]
rtspAddress: 127.0.0.1:8554

# Disable unused protocols to avoid port conflicts
rtmp: no
hls: no
webrtc: no
srt: no

readTimeout: 60s
writeTimeout: 30s

paths:
  stream0:
    source: rtsp://placeholder
    rtspTransport: udp
    sourceOnDemand: no
